### ISSUE TITLE
docs bug in 10 minute tutorial

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#107]
Starting to see the docs builds fail on occasion when running the "update" step of the model in the little `10min.rst` example. An example of the full build log can be found [here](https://pipelines.actions.githubusercontent.com/r7HYedQEmHQHQBwfjmLG4qjELkuVlBiUTJlWnmnEwfY0mcZqUf/_apis/pipelines/1/runs/50/signedlogcontent/13?urlExpires=2020-11-01T20%3A15%3A07.2437481Z&urlSigningMethod=HMACV1&urlSignature=8t3jU5R3z1mRK8LpwxaLiZ%2F%2FixWTUQ%2Fpvm4MqfJjfY8%3D).

An excerpt of the error return from the log file is below.

```
Document: guides/10min
----------------------
**********************************************************************
File "guides/10min.rst", line 21, in default
Failed example:
    for _ in range(0, 5):
        delta.update()
Exception raised:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 2, in <module>
        delta.update()
      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pyDeltaRCM-1.2.0-py3.8.egg/pyDeltaRCM/model.py", line 117, in update
        self.run_one_timestep()
      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pyDeltaRCM-1.2.0-py3.8.egg/pyDeltaRCM/iteration_tools.py", line 60, in run_one_timestep
        self.sed_route()
      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pyDeltaRCM-1.2.0-py3.8.egg/pyDeltaRCM/sed_tools.py", line 27, in sed_route
        self.route_all_sand_parcels()
      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pyDeltaRCM-1.2.0-py3.8.egg/pyDeltaRCM/sed_tools.py", line 50, in route_all_sand_parcels
        self._sr.run(start_indices, self.eta, self.stage, self.depth,
      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/experimental/jitclass/boxing.py", line 60, in wrapper
        return method(*args, **kwargs)
    ValueError: unable to broadcast argument 2 to output array
    File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pyDeltaRCM-1.2.0-py3.8.egg/pyDeltaRCM/shared_tools.py", line 1, 
**********************************************************************
```

**Comment by amoodie** [comment]
I think this is the same as #75? I worked up a "fix" to the bug at some point here #97, but unfortunately it seemed to have broken something else, so it wasn't really a fix. 

In short, yes, this is still a bug that needs to be fixed. It arises almost only when the domain is very small (e.g., the docs examples), but it still should be fixed.

**Comment by elbeejay** [comment]
Could be the case and it has just thrown a different error now that the routing is jitted. Will just be that much more satisfying for whoever solves it and closes 2 issues.

**Comment by amoodie** [comment]
for help in debugging this:

enter into terminal before running `export NUMBA_DISABLE_JIT=1`

Here is an example non-jitted error
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/deltarcm/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/preprocessor.py", line 350, in run
    self.deltamodel.update()
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/model.py", line 119, in update
    self.run_one_timestep()
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/iteration_tools.py", line 55, in run_one_timestep
    self.sed_route()
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/sed_tools.py", line 27, in sed_route
    self.route_all_sand_parcels()
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/sed_tools.py", line 50, in route_all_sand_parcels
    self._sr.run(start_indices, self.eta, self.stage, self.depth,
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/sed_tools.py", line 419, in run
    self._route_one_parcel(px, py)
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/sed_tools.py", line 463, in _route_one_parcel
    self._partition_sediment(px0, py0, px, py, dist)
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/sed_tools.py", line 478, in _partition_sediment
    self.qs[px, py] += partition  # deposition in new cell
IndexError: index 80 is out of bounds for axis 1 with size 80
```

**Comment by amoodie** [comment]
came upon another (un?)related error:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/deltarcm/bin/pyDeltaRCM", line 33, in <module>
    sys.exit(load_entry_point('pyDeltaRCM', 'console_scripts', 'pyDeltaRCM')())
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/preprocessor.py", line 558, in preprocessor_wrapper
    pp.run_jobs()
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/preprocessor.py", line 263, in run_jobs
    job.run_job()
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/preprocessor.py", line 313, in run_job
    self.deltamodel.update()
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/model.py", line 118, in update
    self.run_one_timestep()
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/iteration_tools.py", line 57, in run_one_timestep
    self.run_water_iteration()
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/water_tools.py", line 61, in run_water_iteration
    new_direction = _choose_next_direction(current_inds, water_weights_flat)
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/water_tools.py", line 399, in _choose_next_direction
    new_cells.append(shared_tools.random_pick(weight))
  File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/shared_tools.py", line 73, in random_pick
    return arr[np.searchsorted(np.cumsum(prob), get_random_uniform(1))]
IndexError: index 9 is out of bounds for axis 0 with size 9
```
