### ISSUE TITLE
Documentation Broken

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#262]
See https://github.com/DeltaRCM/pyDeltaRCM/actions/runs/3365355933/jobs/5580741273

Excerpt from logs:

```
/home/runner/work/pyDeltaRCM/pyDeltaRCM/docs/source/info/hydrodynamics.rst:78: WARNING: Exception occurred in plotting _accumulate_free_surface_walks
 from /home/runner/work/pyDeltaRCM/pyDeltaRCM/docs/source/pyplots/water_tools/_accumulate_free_surface_walks.py:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 515, in _run_code
    exec(code, ns)
  File "<string>", line 84, in <module>
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2267, in tight_layout
    return gcf().tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/matplotlib/figure.py", line 3447, in tight_layout
    self.set_layout_engine(engine)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/matplotlib/figure.py", line 2589, in set_layout_engine
    raise RuntimeError('Colorbar layout of new layout engine not '
RuntimeError: Colorbar layout of new layout engine not compatible with old engine, and a colorbar has been created.  Engine not changed.
/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pyDeltaRCM-2.1.4-py3.8.egg/pyDeltaRCM/water_tools.py:docstring of pyDeltaRCM.water_tools._accumulate_free_surface_walks:24: WARNING: Exception occurred in plotting _accumulate_free_surface_walks
 from /home/runner/work/pyDeltaRCM/pyDeltaRCM/docs/source/pyplots/water_tools/_accumulate_free_surface_walks.py:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 515, in _run_code
    exec(code, ns)
  File "<string>", line 84, in <module>
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/matplotlib/pyplot.py", line [226](https://github.com/DeltaRCM/pyDeltaRCM/actions/runs/3365355933/jobs/5580741273#step:6:227)7, in tight_layout
    return gcf().tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/matplotlib/figure.py", line 3447, in tight_layout
    self.set_layout_engine(engine)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/matplotlib/figure.py", line 2589, in set_layout_engine
    raise RuntimeError('Colorbar layout of new layout engine not '
RuntimeError: Colorbar layout of new layout engine not compatible with old engine, and a colorbar has been created.  Engine not changed.
looking for now-outdated files... none found
```

**Comment by amoodie** [comment]
[This change to the API was (one of) the culprit(s)](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#incompatible-layout-engines-raise). This use used to warn, but now raises an error. I think the issue was we used a gridspec in one location then tried to `tight_layout()`, which apparently is incompatible 🤷 

The other issue was a broken github actions build badge url. just updated that to the new badge location.

fixed with #263
