### ISSUE TITLE
Index Error  /  Segmentation fault 

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#53]
This configuration:
```yaml
seed: 42
Length: 20.
Width: 10.
dx: 2
verbose: 1
Np_water: 20
Np_sed: 20
f_bedload: 0.65
```

Leads to an index error:
```python
Traceback (most recent call last):
  File "script/segfault.py", line 10, in <module>
    delta.update()
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/model.py", line 91, in update
    self.run_one_timestep()
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/deltaRCM_tools.py", line 61, in run_one_timestep
    self.run_water_iteration()
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/water_tools.py", line 100, in run_water_iteration
    current_inds = self.check_for_boundary(current_inds)
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/water_tools.py", line 243, in check_for_boundary
    self.free_surf_flag[(self.cell_type.flat[inds] == -1) & (self.free_surf_flag == 0)] = 1
IndexError: index 52 is out of bounds for size 50
```

Similarly, [the tests here and following commented tests](https://github.com/amoodie/pyDeltaRCM_WMT/blob/37eab503941f2733c944d4fd5bcb22cff2f31987/tests/test_shared_tools.py#L231) all produce the same error at the same place when run as scripts, so I believe this may be a pretty common bug. The commented tests produce segmentation faults when run in the testing suite for some reason, so they are commented out.

I guess this bug might have something to do with the `check_for_loops` function which was recently jitted, because this function modifies the `inds` variable in the error above.

**Comment by amoodie** [comment]
Question: are there limitations you are aware of on
* minimum size of the domain
* aspect ratio (Width / Length) limit of the domain
* other limits

If this bug is because the domain is just too small, we should add validation in the `init_tools` to throw errors.

**Comment by elbeejay** [comment]
> Question: are there limitations you are aware of on
> 
> * minimum size of the domain
> * aspect ratio (Width / Length) limit of the domain
> * other limits
> 

I don't know of any limitations although I would expect to have problems if the domain width was less than the inlet channel width, or the length was too small to define the channel/ocean cell types. So I'd agree with the **bug** tag, I guess this is something we need to sort out.

**Comment by amoodie** [comment]
The following config results in the same error of #53 

```yaml
out_dir: 'out_dir'
Length: 10.0
Width: 10.0
dx: 1.0
save_dt: 5
save_strata: False
itermax: 1
Np_water: 10
h0: 1.0
Np_sed: 10
f_bedload: 0.5
C0_percent: 0.1
```

here is the error:

```python
pyDeltaRCM --config ../../research/stratigraphy/pyDeltaRCM/yaml/double.yml --timesteps 2
Traceback (most recent call last):
  File "/opt/anaconda3/bin/pyDeltaRCM", line 11, in <module>
    load_entry_point('pyDeltaRCM', 'console_scripts', 'pyDeltaRCM')()
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/preprocessor.py", line 343, in preprocessor_wrapper
    pp.run_jobs()
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/preprocessor.py", line 123, in run_jobs
    job.run_job()
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/preprocessor.py", line 167, in run_job
    self.deltamodel.update()
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/model.py", line 95, in update
    self.run_one_timestep()
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/deltaRCM_tools.py", line 65, in run_one_timestep
    self.run_water_iteration()
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/water_tools.py", line 100, in run_water_iteration
    current_inds = self.check_for_boundary(current_inds)
  File "/home/andrew/Dropbox/software/pyDeltaRCM_WMT/pyDeltaRCM/water_tools.py", line 244, in check_for_boundary
    self.free_surf_flag[(self.cell_type.flat[inds] == -1) & (self.free_surf_flag == 0)] = 1
IndexError: index 105 is out of bounds for size 100
double free or corruption (!prev)
Aborted (core dumped)
```


but adding the following keys makes the model NOT fail. 
```yaml
N0_meters: 2.0
L0_meters: 1.0
```

I'm posting this to say: I guess it probably relates to these parameters, and the default values for these parameters (`L0_meters: 150.0`; `N0_meters: 200.0`) being too large. 

I guess to resolve this error it would be good to make sure we understand _why_ this fails, and then adding a `ValueError` if the configuration is bad. We should also update docs accordingly.
